// This file is generated by Slice Machine. Update with care!

import ContactForm from './ContactForm';
import Image from './Image';
import IndexItem from './IndexItem';
import Quote from './Quote';
import Text from './Text';

export {
	ContactForm,
	Image,
	IndexItem,
	Quote,
	Text,
};

export const components = {
	contact_form: ContactForm,
	image: Image,
	index_item: IndexItem,
	quote: Quote,
	text: Text,
};
